#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
    path: /
    controller: App\Controller\HomeController::home

app_show:
    path: /article/{slug}
    controller: App\Controller\HomeController::show

app_listarticle:
    path: /listarticle
    controller: App\Controller\ArticleListController::listarticle